from django.conf.urls import url

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # url(r'^$', views.index, name='comments_index'),

    # url(r'^all/$', views.redirect_comments, name='comments'),
    # url(r'^details/$', views.redirect_comments_details, name='comments_details'),
    # url(r'^close/$', views.redirect_comments_close, name='comments_close'),
    # url(r'^create/$',views.redirect_comments_create,name='comments_create'),
    # url(r'^redirect_bizs/$', views.redirect_bizs, name='bizs'),

    url(r'^redirect_statement_lab_order_daily/$', views.redirect_statement_lab_order_daily,
        name='statement_lab_order_daily'),

    url(r'^redirect_statement_lab_order_daily_csv/$', views.redirect_statement_lab_order_daily_csv,
        name='statement_lab_order_daily_csv'),
    url(r'^redirect_statement_lab_order_month/$', views.redirect_statement_lab_order_month,
        name='statement_lab_order_month'),
    url(r'^redirect_statement_lab_order_month_csv/$', views.redirect_statement_lab_order_mouth_csv,
        name='statement_lab_order_month_csv'),
    url(r'^purchase_request_notes_list/$', views.redirect_purchase_request_notes_list,
        name='purchase_request_notes_list'),
    url(r'^purchase_request_notes_new/$', views.redirect_purchase_request_notes_new,
        name='purchase_request_notes_new'),
    url(r'^purchase_request_notes_new_list/$', views.redirect_purchase_request_notes_new_list,
        name='purchase_request_notes_new_list'),
    url(r'^purchase_request_notes_del/$', views.redirect_purchase_request_notes_del,
        name='purchase_request_notes_del'),
    url(r'^purchase_request_notes_save/$', views.redirect_purchase_request_notes_save,
        name='purchase_request_notes_save'),
    url(r'^purchase_request_notes_change_status/$', views.redirect_purchase_request_notes_change_status,
        name='purchase_request_notes_change_status'),
    url(r'^purchase_request_notes_submit/$', views.redirect_purchase_request_notes_submit,
        name='purchase_request_notes_submit'),
    url(r'^purchase_plan_list/$', views.redirect_purchase_plan_list,
        name='purchase_plan_list'),
    url(r'^purchase_plan_new/$', views.redirect_purchase_plan_new,
        name='purchase_plan_new'),
    url(r'^purchase_plan_del/$', views.redirect_purchase_plan_del,
        name='purchase_plan_del'),
    url(r'^purchase_plan_save/$', views.redirect_purchase_plan_save,
        name='purchase_plan_save'),
    url(r'^purchase_plan_change_status/$', views.redirect_purchase_plan_change_status,
        name='purchase_plan_change_status'),
    url(r'^purchase_plan_submit/$', views.redirect_purchase_plan_submit,
        name='purchase_plan_submit'),
    url(r'^purchase_order_list/$', views.redirect_purchase_order_list,
        name='purchase_order_list'),
    url(r'^purchase_order_new/$', views.redirect_purchase_order_new,
        name='purchase_order_new'),
    url(r'^purchase_order_view_edit/$', views.redirect_purchase_order_view_edit,
        name='purchase_order_view_edit'),
    url(r'^purchase_orderitem_del/$', views.redirect_purchase_orderitem_del,
        name='purchase_orderitem_del'),
    url(r'^purchase_order_submit/$', views.redirect_purchase_order_submit,
        name='purchase_order_submit'),
    url(r'^purchase_order_update/$', views.redirect_purchase_order_update,
        name='purchase_order_update'),
    url(r'^purchase_order_complete/$', views.redirect_purchase_order_complete,
        name='purchase_order_complete'),
    url(r'^purchase_order_change_status/$', views.redirect_purchase_order_change_status,
        name='purchase_order_change_status'),
    url(r'^purchase_receipt_order_list/$', views.redirect_purchase_receipt_order_list,
        name='purchase_receipt_order_list'),
    url(r'^purchase_receipt_order_new/$', views.redirect_purchase_receipt_order_new,
        name='purchase_receipt_order_new'),
    url(r'^purchase_add_order/$', views.redirect_purchase_add_order,
        name='purchase_add_order'),
    url(r'^purchase_receipt_order_view_edit/$', views.redirect_purchase_receipt_order_view_edit,
        name='purchase_receipt_order_view_edit'),
    url(r'^purchase_return_order_list/$', views.redirect_purchase_return_order_list,
        name='purchase_return_order_list'),
    url(r'^purchase_return_order_new/$', views.redirect_purchase_return_order_new,
        name='purchase_return_order_new'),
    url(r'^purchase_return_order_submit/$', views.redirect_purchase_return_order_submit,
        name='purchase_return_order_submit'),
    url(r'^purchase_return_order_view_edit/$', views.redirect_purchase_return_order_view_edit,
        name='purchase_return_order_view_edit'),
    url(r'^purchase_return_order_change_status/$', views.redirect_purchase_return_order_change_status,
        name='purchase_return_order_change_status'),
]

# url(r'^mgmt/$', views.index, name='mgmt'),
