# -*- coding: utf-8 -*-
"""
Django settings for pg_oms project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

import logging

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Run Directory
RUN_DIR = '/Users/guof/Documents/Workspaces/Payne/pg_oms'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b(g#xyy=1+$10q24d@-ej(t!!w!5f3evf%sfzy=bpt#_7yr2@k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    'api',
    'tracking',
    'mrp',

    'oms',
    'report',
    'comment',
    'wms',
    'shipment',
    'qc',
    'purchase',
    'workshop',
    'merchandising',
    'vendor',
    'ra',
    'accsorder',
    'stockorder',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_COOKIE_AGE = 60 * 120  # 30 Min

SESSION_SAVE_EVERY_REQUEST = True

ROOT_URLCONF = 'pg_oms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pg_oms.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
DATABASES = {
'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pg_oms_dev',
        'USER': 'pg_dev',
        'PASSWORD': 'pg_dev',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    },

    'pg_oms_query': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pg_oms_dev',
        'USER': 'pg_dev',
        'PASSWORD': 'pg_dev',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    },

    'pg_mg_query': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pg_oms_dev',
        'USER': 'pg_dev',
        'PASSWORD': 'pg_dev',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    },

    'magentodb': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pg_oms_dev',
        'USER': 'pg_dev',
        'PASSWORD': 'pg_dev',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"
# STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, 'static'),
#    os.path.join(BASE_DIR, "static/js"),
#    os.path.join(BASE_DIR, "static/css"),
#    os.path.join(BASE_DIR, "static/images"),
#    os.path.join(BASE_DIR, "static/json"),
#    os.path.join(BASE_DIR, "static/fonts"),
# ]


LOGIN_URL = '/oms/accounts/login/'

# logging debug code.
logging.basicConfig(
    level=logging.DEBUG,
    # format = '%(asctime)s %(levelname)s %(message)s',

    format='%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s',

    # filename='myapp.log',
    # filemode='w'
)
BASE_URL = 'http://beta3.payneglasses.com:450/rest/'
USERNAME = "Api"
PASSWORD = "cZHY0TSSkBdIIqYy"
PUSH_DATE_URL = 'https://beta.payneglasses.com/rest/default/'
pageSize = 15
# 直径计算接口
CALCULATE_DIAMETER_URL = 'http://rules.payneglasses.com/api/v4.0/calculates/'
# 直径计算接口 V2
CALCULATE_DIAMETER_URL_V2 = 'http://rules.payneglasses.com/api/v4.0/calculates_po/'

# 生成二维码，条形码配置
# SCAN_TYPE = ['qr', 'c39', 'c128']
SCAN_TYPE = ['c128']
# pim_box接口
PIM_BOX = "http://192.168.56.101:8001/shipments/receiveBox/"
ADDRESS_URL = "http://192.168.56.101:8001/shipments/new/"
SHIP_ROOT_URL = "http://127.0.0.1:8002"
SHIP_PATH_POST_BOX = "/dc/glasses_box/new/"

MG_ROOT_URL = 'https://test.kyoye.com'
PRODUCT_IMAGE_PATH = '/media/catalog/product'

PROFILE_ROOT_URL = 'http://profile.payneglasses.com'
PROFILE_ORDER_IMAGE_URL = '/order/get_order_image/'

EASYPOST_API_KEY = ''
EASYPOST_BASE_URL = 'https://api.easypost.com/'
EASYPOST_ADDRESS = 'v2/addresses'

MG_API_BASE_URL='https://www.payneglasses.com/'
MG_USERNAME='api'
MG_PASSWORD='cZHY0TSSkBdIIqYy_prd8'

# 取消保险接口
CANCELWARRENTY_BASE_URL = 'https://beta3.payneglasses.com:444/'
CANCELWARRENTY_ADDRESS = 'prescription/open/cancelWarrenty'

BAR_CODE_PREFIX = 'B'

# 工厂接受批量订单的最小数量限制
LABORDER_BATCH_LIMIT = 10

DONATION_SKU = 'up to $5 maximum'

# VD1 单日订单量限制
VD1_DAILY_LIMIT = 100

# WEB同步接口
PG_SYNC_API_BASE_URL = 'http://localhost:8002/api/'
PG_SYNC_API_TOKEN = 'BWbMVVtioDGEF0KEej8tItoFtDgzUd0ZZUgUoDzr4Bl35pa00EdLDVyZ9LH6SVsm'
PG_SYNC_COMMANDS_URL = 'execute_shells/'
PG_SYNC_COMMAND_REFRESH_PRODUCT_INDEX = '2FmzPyOJa8SvAaiZkcYUBCiiZON23P2ncWLM'
PG_SYNC_IS_POLARIZED_URL = 'http://beta.payneglasses.com:8003/api/v4.0/get_lens_is_polarized/'

# 伟星接口
# WX_SERVICE = 'http://183.193.236.122:8866/Service/Service.svc',
WX_SERVICE = 'http://www.qulee.ltd/pic_site/test',
WX_PURCHASE = {
    # 获取账套列表
    'WX_SERVICE_ACCOUNTS': '%s/Accounts' % WX_SERVICE,
    # 创建车房订单
    'WX_SERVICE_ORDER_ADD': '%s/Order/Add' % WX_SERVICE,
    # 更新订单状态
    'WX_SERVICE_ORDER_STATUS_UPDATE': '%s/Order/Status/Update' % WX_SERVICE,
    #获取伟星订单状态
    'WX_ORDER_STATUS': '%s/Order/Status/Get' % WX_SERVICE
}

# 请求ED接口
MG_ED_URL = 'http://rules2.payneglasses.com/api/v4.0/get_product_info/'

# Lab Order 中PG订单号码长度
ORDER_NUMBER_LENGTH = 5
PG_INVENTORY_HOST = "http://beta3.payneglasses.com:451/"
# MRP接口
MRP_BASE_URL = 'http://47.99.206.137:9103/'

#media 存储地址
SSH_MEDIA_SERVER = {
    'MEDIA_BASE_URL': 'http://oms.zhijingoptical.cn/',#'http://47.99.206.137:9901/', #图片服务器
    'SECRET_KEY': 'C:\\Users\\zjgx0\\.ssh\\id_rsa', #私钥
    'BASE_IP': '47.99.206.137',#sftpip
    'USER_NAME': 'root', #用户名
    'UPLOAD_MEDIA_BASE': '/opt/projects/pg_oms/run/media/',#图片存储位置
    'LOCAL_MEDIA_BASE': '/opt/project/pg_oms/app/media/',#'./static/scan/c128/', #本地图片位置
    'SSH_PORT': 22 #SFTP端口号
}


#Send_email
SEND_EMAIL_CONFIG ={
    'MAIL_HOST': 'email-smtp.us-east-1.amazonaws.com',
    'MAIL_PORT': '587',
    'MAIL_USER': 'AKIAZ5DU34VYXHI2P6BX',
    'MAIL_PASS': 'BIrETh/C5iB2zvBNMUGcQEVDwZMjjCWwPNqMxeqiooFg',
    'SENDER': 'dr.payne@email.payneglasses.com'

}

EMAIL_USE_SSL = False
#PURCHASE接口
PURCHASE_BASE_URL = 'http://3.94.110.12:8008'

NOTICED_CUSTOMER_EST_DATE = False



WX_META_SERVICE = 'https://sjcj.wxgx.com:9851/wxshop'
WX_META_PURCHASE = {
    # 获取令牌URL
    'TOKEN_URL': '/all/account/login',
    #获取现片产品清单
    'WX_META_PRD_URL': '/api/product/listCustomerProducts',
    # 添加订单URL
    'ADD_ORDER_URL': '/api/order/addOrder',
    #获取订单状态URL
    'ORDER_STATUS_URL': '/api/order/getOrderStatus'
}

#CHECK ORDER HOLD接口
CHECK_ORDER_HOLD_URL = 'https://www.payneglasses.com/webyiiapi/hold/hold.html'

#上传发货excel配置
UPLOAD_BASE = '/opt/project/pg_oms/app/media/'
UPLOAD_CONFIG = {
    "UPLOAD_EXCEL_URL": "tmp/",
}

#vca 存储地址
VCA_MEDIA_SERVER = {
    'MEDIA_BASE_URL': 'http://oms.zhijingoptical.cn/',#'http://47.99.206.137:9901/', #图片服务器
    'SECRET_KEY': 'C:\\Users\\zjgx0\\.ssh\\id_rsa', #私钥
    'BASE_IP': '47.99.206.137',#sftpip
    'USER_NAME': 'root', #用户名
    'UPLOAD_MEDIA_BASE': 'D:\\workspaces\\run\\pg_oms\\static',#图片存储位置
    'LOCAL_MEDIA_BASE': '/opt/project/pg_oms/app/media/',#'./static/scan/c128/', #本地图片位置
    'SSH_PORT': 22 #SFTP端口号
}

#AWS_CONFIG
AWS_CONFIG = {
    'AWS_KEY': 'AKIAZ5DU34VY7TESF2HI',
    'AWS_SECRET': '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',
    'BUCKET_NAME': 'pg-pim',
    'REGION_NAME': 'us-west-2',
    'BASE_URL': 'https://pg-pim.s3.amazonaws.com/'
}