from django.conf.urls import url

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mgmt/$', views.index, name='mgmt'),
    # add by ranhy
    url(r'^search_customer_email/$', views.search_customer_email, name='search_customer_email'),
    url(r'^update_customer_email/$', views.update_customer_email, name='update_customer_email'),
    url(r'^update_customer_pwd/$', views.update_customer_pwd, name='update_customer_pwd'),

    url(r'^order_list_new/$', views.order_list_new, name='order_list_new'),
    url(r'^order_list/$', views.order_list, name='order_list'),
    url(r'^serarchMgOrderByNumber/', views.serarchMgOrderByNumber, name="serarchMgOrderByNumber"),
    url(r'^generate_pg_orders/$', views.generate_pg_orders, name='generate_pg_orders'),
    url(r'^generate_spe_pg_order/', views.generate_spe_pg_order, name='generate_spe_pg_order'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^login/$', views.loginHtml, name='login'),
    url(r'^loginOms/$', views.loginOms, name='loginOms'),
    url(r'^accounts/login/', auth_views.login, {'template_name': 'login.html'}),
    url(r'^loginout/$', views.loginout, name="loginout"),
    # url(r'^laborderlist/$', views.laborder_list, name='laborderlist'),
    url(r'^address/$', views.search_address, name='address'),
    url(r'^redirect_order_tracking_report/$', views.redirect_order_tracking_report,
        name='redirect_order_tracking_report'),
    url(r'^ordre_tracking_report/$', views.ordre_tracking_report, name='ordre_tracking_report'),
    url(r'^orderTrackingReportFilter', views.orderTrackingReportFilter, name='orderTrackingReportFilter'),
    url(r'^forbid/$', views.forbid, name='forbid'),
    url(r'^rolesHtml/$', views.rolesHtml, name='rolesHtml'),
    url(r'^get_permissions/$', views.get_permissions, name='get_permissions'),
    url(r'^permission/$', views.permissions, name='permission'),
    url(r'^laborder_status', views.laborder_status, name='laborderstatus'),
    url(r'^final_inspection/', views.final_inspection, name='final_inspection'),
    url(r'^redirectReportCSList', views.redirectReportCSList, name='redirectReportCSList'),
    url(r'^orderTrackingReportCsList', views.orderTrackingReportCsList, name='orderTrackingReportCsList'),
    url(r'^action_status', views.action_status, name='actionStatus'),
    url(r'^redirectPgOrderItemList', views.redirectPgOrderItemList, name='redirectPgOrderItemList'),
    # url(r'^queryPgOrderItems', views.queryPgOrderItems, name='queryPgOrderItems'),

    url(r'^pg_order_review', views.pg_order_review, name='pg_order_review'),
    url(r'^pg_order_cancel_review', views.pg_order_cancel_review, name='pg_order_cancel_review'),
    url(r'^pg_order_approve', views.pg_order_approve, name='pg_order_approve'),

    url(r'^generateLabOrders', views.generateLabOrders, name='generateLabOrders'),
    url(r'^queryActivities', views.queryActivities, name='queryActivities'),
    url(r'^pgOrderItemList', views.pgOrderItemList, name='pgOrderItemList'),
    url(r'^pgOrderItemFilter', views.pgOrderItemFilter, name='pgOrderItemFilter'),
    url(r'^esTime', views.esTime, name='esTime'),
    url(r'^confirmAction', views.confirmAction, name='confirmAction'),
    url(r'^shipmentServer', views.shipmentServer, name='shipmentServer'),
    url(r'^pgorderItemDetail', views.pgorderItemDetail, name='pgorderItemDetail'),
    url(r'^redirectLabOrderList', views.redirectLabOrderList, name='redirectLabOrderList'),
    url(r'^labOrderLists', views.labOrderList, name='labOrderList'),
    url(r'^labOrderDetail', views.labOrderDetail, name='labOrderDetail'),
    url(r'^labOrderListcount', views.labOrderListcount, name='labOrderListcount'),
    url(r'^labOrderLog', views.labOrderLog, name='labOrderLog'),
    url(r'^labOrderHold', views.labOrderHold, name='labOrderHold'),
    url(r'^lab_order_hold_v2', views.lab_order_hold_v2, name='lab_order_hold_v2'),
    url(r'^labOrderCancelled', views.labOrderCancelled, name='labOrderCancelled'),
    url(r'^lab_order_cancelled_v2', views.lab_order_cancelled_v2, name='lab_order_cancelled_v2'),
    url(r'^labOrderRedo', views.labOrderRedo, name='labOrderRedo'),
    url(r'^redirectOrderAddress', views.redirectOrderAddress, name='redirectOrderAddress'),
    url(r'^redirectChangePassword', views.redirectChangePassword, name='redirectChangePassword'),
    url(r'^changePassword', views.changePassword, name='changePassword'),
    url(r'^addComments', views.addComments, name='addComments'),
    url(r'^send_invoice', views.send_invoice, name='send_invoice'),
    url(r'^changeComments', views.changeComments, name='changeComments'),
    url(r'^pgorder_status/$', views.pgorder_status, name='pgorder_status'),
    url(r'^pgorder_status_v3/$', views.pgorder_status_v3, name='pgorder_status_v3'),
    url(r'^redirectPgOrderList', views.redirectPgOrderList, name='redirectPgOrderList'),
    url(r'^pgOrderList', views.pgOrderList, name='pgOrderList'),
    # url(r'^generate_pgorders_mig', views.generate_pgorders_mig, name='generate_pgorders_mig'),
    # url(r'^generate_pgorderitem_mig', views.generate_pgorderitem_mig, name='generate_pgorderitem_mig'),
    url(r'^pgOrderUpdate', views.pgOrderUpdate, name='pgOrderUpdate'),
    # url(r'^pgOrderItemDetail',views.pgOrderItemDetail,name='pgOrderItemDetail'),
    url(r'^pgOrderItemUpdate', views.pgOrderItemUpdate, name='pgOrderItemUpdate'),
    url(r'^print_laborder', views.print_lab_order, name='print_laborder'),
    url(r'^sendAPI', views.order_comment),
    url(r'^send_message', views.send_message),
    url(r'^get_entity', views.get_entity, name='get_entity'),
    url(r'^dealComments', views.deal_comments),
    url(r'^dashboard/getNumber/', views.getNumber),
    url(r'^dashboard/getPageInfo/', views.getPageInfo),
    url(r'^pgOrderSetInLab/', views.pgOrderSetInLab),
    url(r'^pgOrderPushDate/', views.pushDate),
    url(r'^getOrderItem/$', views.getPgOrder),
    url(r'^redirectShipment/$', views.redirectShipment),
    url(r'^shipmentController/$', views.shipmentController),
    url(r'^getShipmentInfo/$', views.getShipmentInfo),
    url(r'^searchOrderInfo/', views.searchOrderInfo),
    url(r'^searchMatchOrderInfo/', views.searchMatchOrderInfo),
    url(r'^redirectComment/', views.redirectComment),
    url(r'^changeActivitySendStatus/', views.changeSendStatus),

    url(r'^pgorder_list/', views.redirect_pgorder_list),
    url(r'^pgorder_detail/', views.redirect_pgorder_detail),
    url(r'^pgorder_item_detail/', views.redirect_pgorder_item_detail),
    url(r'^pgorder_update/', views.redirect_pgorder_update),

    # url(r'^pgorder_list_v3/3c79364c-d9d5-4ab2-b5a9-89f285f86ebc/$', views.redirect_pgorder_list_v3,
    #     name='pgorder_list_v3'),
    # url(r'^pgorder_detail_v3/6ceeb9b8-ae63-41a3-aea4-d8e60188b84d/$', views.redirect_pgorder_detail_v3,
    #     name='pgorder_detail_v3'),
    # url(r'^pgorder_item_detail_v3/ef2aedd2-f8aa-4942-a618-58f8f65a6e3a/$', views.redirect_pgorder_item_detail_v3,
    #     name='pgorder_item_detail_v3'),
    # url(r'^pgorder_update_v3/58715fff-250c-4f18-9985-b064b603eae2/$', views.redirect_pgorder_update_v3,
    #     name='pgorder_update_v3'),

    url(r'^pgorder_list_v3/$', views.redirect_pgorder_list_v3,
        name='pgorder_list_v3'),
    url(r'^pgorder_detail_v3/$', views.redirect_pgorder_detail_v3,
        name='pgorder_detail_v3'),
    url(r'^pgorder_get_warranty_by_order/$', views.redirect_pgorder_get_warranty_by_order,
        name='pgorder_get_warranty_by_order'),

    url(r'^pgorder_set_priority/$', views.redirect_pgorder_set_priority,
        name='pgorder_set_priority'),

    url(r'^pgorder_item_detail_v3/ef2aedd2-f8aa-4942-a618-58f8f65a6e3a/$', views.redirect_pgorder_item_detail_v3,
        name='pgorder_item_detail_v3'),
    url(r'^pgorder_update_v3/$', views.redirect_pgorder_update_v3,
        name='pgorder_update_v3'),
    url(r'^prescripion_update_v3/$', views.redirect_prescripion_update_v3,
        name='prescripion_update_v3'),

    url(r'^laborder_request_notes/', views.redirect_laborder_request_notes,
        name='laborder_request_notes'),
    url(r'^laborder_request_notes_archives/', views.redirect_laborder_request_notes_archives,
        name='laborder_request_notes_archives'),
    url(r'^frame_delivery_list/', views.redirect_frame_delivery_list,
        name='frame_delivery_list'),
    url(r'^frame_delivery_print/', views.redirect_frame_delivery_print,
        name='frame_delivery_print'),

    url(r'^laborder_purchase_orders/', views.redirect_laborder_purchase_orders,
        name='laborder_purchase_orders'),
    url(r'^purchase_orders/', views.redirect_purchase_orders,
        name='purchase_orders'),
    url(r'^purchase_order_line/', views.redirect_purchase_order_line,
        name='purchase_order_line'),
    url(r'^set_purchase_order_is_in_rx/', views.set_purchase_order_is_in_rx,
        name='oms_set_purchase_order_is_in_rx'),
    url(r'^updata_laborder_status_print_date/', views.updata_laborder_status_print_date,
        name='updata_laborder_status_print_date'),
    url(r'^push_purchase_order_to_mrp/', views.push_purchase_order_to_mrp,
        name='push_purchase_order_to_mrp'),

    url(r'^laborder_request_notes_detail/', views.redirect_laborder_request_notes_detail,
        name='laborder_request_notes_detail'),
    url(r'^laborder_request_notes_create/', views.redirect_laborder_request_notes_create,
        name='laborder_request_notes_create'),
    url(r'^laborder_request_notes_generate_barcode/', views.redirect_laborder_request_notes_generate_barcode,
        name='laborder_request_notes_generate_barcode'),

    url(r'^laborder_request_notes_generate_barcode_special/',
        views.redirect_laborder_request_notes_generate_barcode_special,
        name='laborder_request_notes_generate_barcode_special'),

    url(r'^laborder_request_notes_generate_csv/', views.redirect_laborder_request_notes_generate_csv,
        name='laborder_request_notes_generate_csv'),
    url(r'^laborder_purchase_generate_csv/', views.redirect_laborder_purchase_generate_csv,
        name='laborder_purchase_generate_csv'),

    url(r'^laborder_request_notes_generate_csv_wx/', views.redirect_laborder_request_notes_generate_csv_wx,
        name='laborder_request_notes_generate_csv_wx'),
    url(r'^laborder_purchase_generate_csv_wx/', views.redirect_laborder_purchase_generate_csv_wx,
        name='laborder_purchase_generate_csv_wx'),

    url(r'^laborder_request_notes_print/', views.redirect_laborder_request_notes_print,
        name='laborder_request_notes_print'),

    url(r'^redirect_laborder_request_lens_notes_print/', views.redirect_laborder_request_lens_notes_print,
        name='redirect_laborder_request_lens_notes_print'),
    url(r'^redirect_laborder_request_lens_notes_print_count/', views.redirect_laborder_request_lens_notes_print_count,
        name='redirect_laborder_request_lens_notes_print_count'),

    url(r'^laborder_request_notes_delivery/', views.redirect_laborder_request_notes_delivery,
        name='laborder_request_notes_delivery'),

    url(r'^laborder_request_notes_change_vendor/', views.redirect_laborder_request_notes_change_vendor,
        name='laborder_request_notes_change_vendor'),

    url(r'^redirect_construction_voucher/', views.redirect_construction_voucher,
        name='construction_voucher'),
    url(r'^redirect_construction_voucher_print/', views.redirect_construction_voucher_print,
        name='construction_voucher_print'),

    url(r'^redirect_construction_voucher_finished_glasses/', views.redirect_construction_voucher_finished_glasses,
        name='construction_voucher_finished_glasses'),
    url(r'^redirect_construction_voucher_finished_glasses_print/',
        views.redirect_construction_voucher_finished_glasses_print,
        name='construction_voucher_finished_glasses_print'),

    url(r'^redirect_construction_voucher_finished_glasses_print_v3/',
        views.redirect_construction_voucher_finished_glasses_print_v3,
        name='construction_voucher_finished_glasses_print_v3'),

    url(r'^redirect_laborder_list_v2/', views.redirect_laborder_list_v2,
        name='laborder_list_v2'),

    url(r'^redirect_laborder_list_v2_qa/', views.redirect_laborder_list_v2_qa,
        name='laborder_list_v2_qa'),

    url(r'^redirect_laborder_detail_v2/', views.redirect_laborder_detail_v2,
        name='laborder_detail_v2'),
    url(r'^redirect_laborder_detail_pspf/', views.redirect_laborder_detail_pspf,
        name='laborder_detail_pspf'),
    url(r'^export_excel/', views.export_excel,
        name='export_excel'),
    url(r'^redirect_laborder_detail/(.*)/$', views.redirect_laborder_detail,
        name='laborder_detail'),

    url(r'^distribute_vendor/$', views.distribute_vendor,
        name='distribute_vendor'),

    url(r'^received_glasses/$', views.redirect_received_glasses, name='received_glasses'),
    url(r'^received_glasses_list/$', views.redirect_received_glasses_list, name='received_glasses_list'),
    url(r'^ajax_edit_act_lens/$', views.ajax_edit_act_lens, name='ajax_edit_act_lens'),

    url(r'^edit_process/$', views.edit_process, name='edit_process'),
    url(r'^edit_channel/$', views.edit_channel, name='edit_channel'),
    url(r'^edit_lab_comments/$', views.edit_lab_comments, name='edit_lab_comments'),

    url(r'^get_prescription/$', views.get_prescription, name='get_prescription'),
    url(r'^get_mg_ed/$', views.get_mg_ed, name='get_mg_ed'),

    url(r'^wx_purchasing_order/$', views.wx_purchasing_order, name='wx_purchasing_order'),
    url(r'^wc_purchasing_order/$', views.wc_purchasing_order, name='wc_purchasing_order'),
    url(r'^re_order_v3/$', views.re_order_v3, name='re_order_v3'),
    url(r'^hold_cancel_request/$', views.hold_cancel_request_list, name='hold_cancel_request'),
    url(r'^edit_apply_hold_cancel_request/$', views.edit_apply_hold_cancel_request_list,name='edit_apply_hold_cancel_request'),
    url(r'^apply_hold_cancel_request/$', views.apply_hold_cancel_request_list, name='apply_hold_cancel_request'),
    url(r'^abnormal_list/$', views.abnormal_list, name='abnormal_list'),
    url(r'^get_frame_img/$', views.get_frame_img, name='get_frame_img'),
    url(r'^dashbord_processing_list/$', views.dashbord_processing_list, name='dashbord_processing_list'),
    url(r'^overdue_orders/$', views.redirect_overdue_orders, name='oms_overdue_orders'),
    url(r'^overdue_orders_v2/$', views.redirect_overdue_orders_v2, name='overdue_orders_v2'),
    url(r'^overdue_orders_csv/$', views.redirect_overdue_orders_csv, name='oms_overdue_orders_csv'),
    url(r'^overdue_orders_csv_v2/$', views.redirect_overdue_orders_csv_v2, name='overdue_orders_csv_v2'),
    url(r'^sub_delay_data/$', views.redirect_sub_delay_data,
        name='oms_sub_delay_data'),
    url(r'^edit_laborder_frame/$', views.edit_laborder_frame,
        name='edit_laborder_frame'),
    url(r'^modify_laborder_frame/$', views.modify_laborder_frame,
        name='modify_laborder_frame'),
    url(r'^edit_laborder_sku/$', views.edit_laborder_sku,
        name='edit_laborder_sku'),
    url(r'^modify_laborder_sku/$', views.modify_laborder_sku,
        name='modify_laborder_sku'),
    url(r'^change_frame_sku/$', views.change_frame_sku,
        name='change_frame_sku'),
    url(r'^pgorder_item_detail_v3_nrx/ef2aedd2-f8aa-4942-a618-58f8f65a6e3a/$', views.redirect_pgorder_item_detail_v3_nrx,
        name='pgorder_item_detail_v3_nrx'),
    url(r'^sync_shipment_status/$',
        views.redirect_sync_shipment_status,
        name='sync_shipment_status'),
    url(r'^edit_laborder_shipment/$',
        views.redirect_edit_laborder_shipment,
        name='edit_laborder_shipment'),
    url(r'^edit_hold_to_processing/$',
        views.redirect_edit_hold_to_processing,
        name='edit_hold_to_processing'),
    url(r'^pg_order_reorder/$', views.redirect_pg_order_reorder,name='pg_order_reorder'),
    url(r'^edit_laborder_parameters/$',
        views.redirect_edit_laborder_parameters,
        name='edit_laborder_parameters'),
    url(r'^lens_specmap_add_edit/$', views.redirect_lens_specmap_add_edit, name='oms_lens_specmap_add_edit'),
    url(r'^add_lens_specmap/$', views.redirect_add_lens_specmap, name='oms_add_lens_specmap'),
    url(r'^edit_lens_specmap/$', views.redirect_edit_lens_specmap, name='oms_edit_lens_specmap'),
    url(r'^save_lens_specmap/$', views.redirect_save_lens_specmap, name='oms_save_lens_specmap'),
    url(r'^black_list_edit/$', views.redirect_black_list_edit, name='oms_black_list_edit'),
    url(r'^black_list_modify/$', views.redirect_black_list_modify, name='oms_black_list_modify'),
    url(r'^black_list_add/$', views.redirect_black_list_add, name='oms_black_list_add'),
    url(r'^delivered_time_add/$', views.redirect_delivered_time_add, name='oms_delivered_time_add'),
    url(r'^pause_duration_add/$', views.redirect_pause_duration_add, name='oms_pause_duration_add'),
    url(r'^edit_pgorderitem_dia/$', views.redirect_edit_pgorderitem_dia, name='oms_edit_pgorderitem_dia'),
    url(r'^wx_meta_purchasing_order/$', views.wx_meta_purchasing_order, name='oms_wx_meta_purchasing_order'),

    url(r'^oms_file_download', views.oms_file_download, name='oms_file_download'),


]
# url(r'^mgmt/$', views.index, name='mgmt'),
